create extension if not exists pgcrypto;

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  status text not null default 'Not Started',
  category text not null default 'Clinical',
  impact smallint not null default 3 check (impact between 1 and 5),
  urgency smallint not null default 3 check (urgency between 1 and 5),
  effort smallint not null default 3 check (effort between 1 and 5),
  risk smallint not null default 3 check (risk between 1 and 5),
  due_date date null,
  assigned text not null default '',
  notes text not null default '',
  score smallint not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_tasks_updated_at on public.tasks;
create trigger set_tasks_updated_at
before update on public.tasks
for each row
execute function public.set_updated_at();

alter table public.tasks enable row level security;

drop policy if exists "Allow public read access" on public.tasks;
create policy "Allow public read access"
on public.tasks
for select
using (true);

drop policy if exists "Allow public insert" on public.tasks;
create policy "Allow public insert"
on public.tasks
for insert
with check (true);

drop policy if exists "Allow public update" on public.tasks;
create policy "Allow public update"
on public.tasks
for update
using (true)
with check (true);

drop policy if exists "Allow public delete" on public.tasks;
create policy "Allow public delete"
on public.tasks
for delete
using (true);
